# Generated by Django 3.2 on 2022-10-22 10:54

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mwanachama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mwanachama_jina', models.CharField(max_length=30)),
                ('mwanachama_phone', models.CharField(max_length=20)),
                ('mwanachama_cheo', models.IntegerField(choices=[(0, 'MWENYEKITI'), (1, 'M/MSAIDIZI'), (2, 'MWANACHAMA')], default=2, verbose_name='Nafasi Yako')),
                ('mwanachama_jinsia', models.IntegerField(choices=[(0, 'MALE'), (1, 'FEMALE')], default=0, verbose_name='Jinsia Yako')),
                ('pichayamwanachama', models.ImageField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Ratibayavikao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kikaoagenda', models.TextField()),
                ('sikuyakikao', models.CharField(max_length=30)),
                ('mudawakikao', models.TimeField()),
                ('mahalipakikao', models.CharField(max_length=30)),
                ('tareheyakikao', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Umojawetu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mwanachamajina', models.CharField(max_length=100)),
                ('taarifahusika', models.TextField()),
                ('sikuyatukio', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Mkopo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kiasichamkopo', models.IntegerField()),
                ('tareheyakuombwa', models.DateTimeField()),
                ('tareheyakurudishwa', models.DateTimeField(blank=True, null=True)),
                ('mwanachamaID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chamaapp.mwanachama')),
            ],
        ),
        migrations.CreateModel(
            name='Madeni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kiasikilichowekwa', models.IntegerField()),
                ('tareheyakuwekapesa', models.DateField()),
                ('kiasichamkopokilichobaki', models.IntegerField()),
                ('mkopoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamaapp.mkopo')),
                ('mwanachamaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamaapp.mwanachama')),
            ],
        ),
        migrations.CreateModel(
            name='Dharura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sababuyadharura', models.TextField()),
                ('tareheyadharura', models.DateTimeField(blank=True, null=True)),
                ('sikuyadharurakuombwa', models.DateTimeField(auto_now_add=True)),
                ('mwanachamaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamaapp.mwanachama')),
            ],
        ),
        migrations.CreateModel(
            name='Mtumiaji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
